### ISSUE TITLE
Feature: Integrate Million

### ISSUE THREAD

**Issue by gtrabanco** [BalonmanoVetusta/liveshow-graphics#59]
## Description

Integrate million to make web faster.

## Tasks

- [ ] Install [million](https://million.dev/docs/install)
- [ ] Replace all `.map` to use the `<For />` component.
- [ ] Add million in top level page which makes easier to integrate it. If fail go more atomic and so on until it works.
- [ ] Check performance before and after to know if it really improves the performance.

## Reference

- https://million.dev/docs
