### ISSUE TITLE
[Feature Request] Banners with custom times and properties

### ISSUE THREAD

**Issue by gtrabanco** [BalonmanoVetusta/liveshow-graphics#67]
## Description

Customize banner time, animation and Height individually.

This would be useful to show some temporary data like classification or auto promos with less time than sponsor times or rotation components instead of images.

## TODO
- [ ] Advertising must be in its own NodeCG workspace.
- [ ] A select of banners to show only selected banners.
- [ ] Customize the seconds that it will be showed (optionally). TODO this, time that a banner is showed before transition must be calculated like in the stopwatch.
